//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Service
    {
        public int id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> service_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Service Service { get; set; }
    }
}
