//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public int employee_id { get; set; }
        public int appointment_id { get; set; }
        public int number_check { get; set; }
        public string service_list { get; set; }
        public int service_cost { get; set; }
        public int check_status_id { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual CheckStatus CheckStatus { get; set; }
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
