//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check_Service
    {
        public int id { get; set; }
        public int check_id { get; set; }
        public int service_id { get; set; }
    
        public virtual Check Check { get; set; }
        public virtual Service Service { get; set; }
    }
}
