//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DANT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceList
    {
        public int id { get; set; }
        public string service { get; set; }
        public string cost { get; set; }
    }
}
